name: gliderkmz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - requests=2.31.0
  - pandas=2.2.1
  - numpy=1.26.4
  - simplekml=1.3.6
  - pyyaml=6.0.1
  - Jinja2=3.1.3
  - oceans=1.1.3
  - pip=24.0
  - pip:
    - magnetic-field-calculator==1.0.2
