# from Dave (slack 4/1/2024):
# gps time > 30 minutes red, rest green
# battery < 13.25 red, 14 orange, >14 green
# vacuum < 6 >12.5 red,   rest green
m_battery:
    fail_low: 13.25
    suspect_low: 14
m_vacuum:
    fail_low: 6
    fail_high: 12.5
